[package]
name = "stil_combinator"
version = "0.1.0"
edition = "2018"
authors = ["Komei Higuchi <komekome09@komekome09.jp>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "*"
